version: "2"
services:
  pwn:
    build:
      context: .
      dockerfile: example.Dockerfile
    image: test_base_pwn_native_1604
    volumes:
      - ./tcpdump:/var/lib/tcpdump
    ports:
      - "10000:10000"
    environment:
      - FLAG=ctfhub{base_pwn_xinetd}
      - TCPDUMP_ENABLE=1
